cluster.name: elasticsearch-tests
network.host: 127.0.0.1
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["localhost"]
http.cors.enabled: true
http.cors.allow-origin: /.*/